#spring.profiles.active=local
#spring.datasource.url=jdbc:mysql://localhost:3306/my_movie
#spring.jpa.show-sql=true
#spring.datasource.username=root
#spring.datasource.driver-class-name

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/my_movie
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create